### ISSUE TITLE
CPython 运行时Inject的一些疑问

### ISSUE THREAD

**Issue by shen-buding** [Hackerl/pangolin#5]
https://github.com/bytedance/Elkeid/blob/main/rasp/librasp/src/cpython.rs#L155

Python2.7
1、如果之前没有动态库引入直接Inject会出现如下
![image](https://github.com/Hackerl/pangolin/assets/35806332/9d494156-461b-4783-9bc1-3b1bcc5336f3)
2、如果之前动态库引入过再Inject好像没啥问题
![image](https://github.com/Hackerl/pangolin/assets/35806332/1d74ea1c-76a3-4069-8ebb-dc695f061a5f)

这个Inject是支持常规Inject注入动态库的嘛

**Comment by Hackerl** [comment]
这个 PythonInject 是哪里来的，注入请使用 Elkeid 的 python-loader 二进制。

**Comment by shen-buding** [comment]
是的, 这个PythonInject代码有问题, 用你们Elkeid官方就ok
