### ISSUE TITLE
问个题外话

### ISSUE THREAD

**Issue by shen-buding** [Hackerl/pangolin#6]
RASP 行为序列入侵检测
这个功能能不能举个例子?

RASP 热补丁
热补丁除了Java之外, 其他语言也能热补丁吗?

**Comment by Hackerl** [comment]
这类技术讨论建议邮件沟通。
1. 策略端通过分析 `RASP` 上报数据进行关联和溯源，可以较为准确的定位入侵行为，并可以展示出具体的攻击路径（出问题的代码位置，调用栈详情）。
2. 热补丁依赖于 `JVM` 提供的动态修改 `class` 能力，`Python`、`Node.js` 以及 `PHP` 等动态语言也可以模仿，动态修改业务代码，`Golang` 会编译成机器码无法做到热补丁，但是所有语言都支持阻断抛出错误。
